### ISSUE TITLE
Add support for QRL coin

### ISSUE THREAD

**Issue by ariadarkkkis** [MoneroOcean/xmr-node-proxy#58] opened 2018-08-11 16:51 UTC
Hi
Please add support of this coin, herominers pool already edited MO fork and make it work.
Here is the link:
https://github.com/herominers/xmr-node-proxy-qrl

Thanks

**Comment by djfinch** [comment] 2018-08-11 18:29
QRL is CN/1. Nothing to add here, it should work without any action... 

They just created new repo without forking this one and f*#$ed XNP functionality to work with their non-nodejs-pool... Also with some issues which were already fixed here (their copied version is 1.6)
![image](https://user-images.githubusercontent.com/13107713/43994910-151c980e-9da5-11e8-88c8-34a176c9afb7.png)

Conclusion:
You need nodejs-pool and this proxy will work like a charm (I think).

**Comment by MoneroOcean** [comment] 2018-08-21 11:37
@djfinch Thanks! OK, will close this for now. @ariadarkkkis If still actual please reopen it.

**Closed by MoneroOcean** 2018-08-21 11:37 UTC

**Comment by untoreh** [comment] 2018-08-31 18:58
tested on `Pool.QRL.CryptoPool.Space` which is standard nodejs doesn't work either so the problem is not on the pool end.
```
Error: Failed to parse block
```
maybe qrl uses a custom blob?

**Comment by bkmy625** [comment] 2020-10-20 22:12
QRL has made some changes to theyre algo. they are randomx now or they changed the blob too i dont know
These answers don't work anymore

Can someone update xmr node so it can support the new QRL changes
